runtime: python310

entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

env_variables:
  GOOGLE_MAPS_API_KEY: "AIzaSyCLCf-a0Mug12YWgOtJ3kwVbRJWM4nU7Mw"
  GEMINI_API_KEY: "AIzaSyBhiNR_H7KjZfgYBrFNKkcxgDXj7a8DB8Y"
  SUPABASE_URL: "https://wymhiscfhjjkahfscmly.supabase.co"
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5bWhpc2NmaGpqa2FoZnNjbWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MDIwOTMsImV4cCI6MjA3NTI3ODA5M30.pqlOysczSzK0vKfKOjr0MjB3-Ek8xV_1pXf_WYEpY7U"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
  - url: /.*
    script: auto
